name: CI

on: [push, pull_request]

jobs:
  examples:
    name: Examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    services:
      yamcs:
        image: yamcs/example-simulation
        ports:
          - 8090:8090
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Set up yamcs-client
        run: |
          python -m pip install --upgrade pip
          cd yamcs-client
          python -m pip install -e .
      - name: Run examples
        run: |
          cd yamcs-client/examples
          ./run-all.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: flake8 . --exclude '*pb2.py' --count --show-source --statistics

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Set up sphinx
        run: |
          python -m pip install --upgrade pip
          pip install -r yamcs-client/requirements.txt
          pip install -r docs/requirements.txt
      - name: Generate documentation
        run: |
          cd yamcs-client
          python -m pip install -e .
          cd ../docs
          make html
